name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions: write-all
    name: Publish binaries
    runs-on: ubuntu-latest
    container: fedora:39

    steps:
    - uses: actions/checkout@v3

    - name: Check version consistency
      run: bash scripts/version-check.sh

    - name: Check tag name matches
      run: if [ "${{github.ref_name}}" = "$(scripts/version-check.sh)" ]; then exit 0; else exit 1; fi

    - name: Dependencies
      run: sudo dnf install -y libadwaita-devel gtk4-devel make cargo gettext-devel zip

    - name: Build
      run: cargo build --release

    - name: Make Zip
      run: |
        mkdir BoxBuddy-${{github.ref_name}}
        mv target/release/boxbuddy-rs BoxBuddy-${{github.ref_name}}
        mv scripts/install.sh BoxBuddy-${{github.ref_name}}
        mv scripts/uninstall.sh BoxBuddy-${{github.ref_name}}
        cp -r po BoxBuddy-${{github.ref_name}}/
        mv icons/io.github.dvlv.boxbuddyrs.svg BoxBuddy-${{github.ref_name}}/
        mv io.github.dvlv.boxbuddyrs.desktop BoxBuddy-${{github.ref_name}}/
        zip -r BoxBuddy-${{github.ref_name}}.zip BoxBuddy-${{github.ref_name}}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: BoxBuddy-${{github.ref_name}}.zip
        asset_name: BoxBuddy-${{github.ref_name}}.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
        prerelease: true
